name: LbEvents
version: 1.0
main: com.craftlias.lbevents.LbEvents
api-version: '1.21'
commands:
  lbevents:
    description: LbEvents ana yönetim komutu.
    aliases: [lbevent]
permissions:
  lbevents.admin:
    description: Tüm LbEvents komutlarını kullanabilir.
    default: op
  lbevents.start:
    description: Etkinlikleri başlatabilir.
    default: op
  lbevents.stop:
    description: Etkinlikleri durdurabilir.
    default: op
  lbevents.reload:
    description: Config dosyalarını yeniler.
    default: op